// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akonlzlpbdoqmczidfwm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrb25semxwYmRvcW1jemlkZndtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NTcxMjMsImV4cCI6MjA2NjEzMzEyM30.Aqc8YNgNPhnoKErL5FqnwHUnejVhuaRVGel9sm2PJHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);